post http://localhost:3060/api/login
Content-Type: application/json

{ "email": "pablo@email.com", "password": "12345" }

###
post http://localhost:3060/api/user/create
Content-Type: application/json

{ "firstname": "Pablo", "lastname": "Barletti", "email": "pablo@email.com", "password": "12345" }


###
post http://localhost:3060/api/appointment/book
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdG5hbWUiOiJQYWJsbyIsImxhc3RuYW1lIjoiQmFybGV0dGkiLCJpYXQiOjE3MzQ5MTYzNjAsImV4cCI6MTczNDkxNjk2MH0.XP0DSbzLGUztXhrY2vy7hIp8NNBcctTSslVtA6SNk_o

{
    "countryIso": "MX", 
    "patientId": 55000, 
    "medicId": 50, 
    "scheduleId": 123, 
    "centerId": 6
}